# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TracMobility' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TracMobility
	pod 'Auth0', '~> 1.0'
	pod 'SideMenu'
  	pod 'GoogleMaps', '4.0.0'


end
